### ISSUE TITLE
this should never happen: scheduleCheckIfStillActive() timeout

### ISSUE THREAD

**Issue by Ilovegym66** [Acgua/ioBroker.fully-mqtt#25]
Hi,
found this in the log:
```
2023-04-02 07:55:49.195  - info: fully-mqtt.0 (8495) 🔗 MQTT Client Huawei-SchlafzLinks (10.1.1.52) successfully connected.
2023-04-02 07:55:49.195  - info: fully-mqtt.0 (8495) Huawei-SchlafzLinks is alive (MQTT: client connected)
2023-04-02 07:56:59.288  - warn: fully-mqtt.0 (8495) Huawei-SchlafzLinks is not alive! (MQTT: client did not send message for more than 70 seconds)
2023-04-02 07:57:19.287  - info: fully-mqtt.0 (8495) [MQTT] Huawei-SchlafzLinks: Client error - keep alive timeout
2023-04-02 07:57:19.288  - info: fully-mqtt.0 (8495) MQTT Client Huawei-SchlafzLinks disconnected.
2023-04-02 07:59:40.431  - info: fully-mqtt.0 (8495) 🔑 MQTT Client Huawei-SchlafzLinks (10.1.1.52) successfully authenticated.
2023-04-02 07:59:40.431  - info: fully-mqtt.0 (8495) 🔗 MQTT Client Huawei-SchlafzLinks (10.1.1.52) successfully connected.
2023-04-02 07:59:40.431  - info: fully-mqtt.0 (8495) Huawei-SchlafzLinks is alive (MQTT: client connected)
2023-04-02 08:01:56.949  - warn: fully-mqtt.0 (8495) Huawei-SchlafzLinks is not alive! (MQTT: client did not send message for more than 70 seconds)
2023-04-02 08:02:16.949  - info: fully-mqtt.0 (8495) [MQTT] Huawei-SchlafzLinks: Client error - keep alive timeout
2023-04-02 08:02:16.950  - info: fully-mqtt.0 (8495) MQTT Client Huawei-SchlafzLinks disconnected.
2023-04-02 08:03:56.304  - info: fully-mqtt.0 (8495) 🔑 MQTT Client Huawei-SchlafzLinks (10.1.1.52) successfully authenticated.
2023-04-02 08:03:56.304  - info: fully-mqtt.0 (8495) 🔗 MQTT Client Huawei-SchlafzLinks (10.1.1.52) successfully connected.
2023-04-02 08:03:56.304  - info: fully-mqtt.0 (8495) Huawei-SchlafzLinks is alive (MQTT: client connected)
2023-04-02 08:06:15.972  - **warn: fully-mqtt.0 (8495) [MQTT] Huawei-SchlafzLinks (10.1.1.52) Please open a issue on Github, this should never happen: scheduleCheckIfStillActive() timeout, and last contact was less than 70s ago.**
2023-04-02 08:06:15.972  - warn: fully-mqtt.0 (8495) [MQTT] Huawei-SchlafzLinks (10.1.1.52) is alive - last contact 70s (70000ms) ago
2023-04-02 08:06:35.973  - info: fully-mqtt.0 (8495) [MQTT] Huawei-SchlafzLinks: Client error - keep alive timeout
2023-04-02 08:06:35.973  - warn: fully-mqtt.0 (8495) Huawei-SchlafzLinks is not alive! (MQTT: client error)
2023-04-02 08:06:35.973  - info: fully-mqtt.0 (8495) MQTT Client Huawei-SchlafzLinks disconnected.
````
_(edited by Acgua: added tag for multiple line code)_

**Comment by Acgua** [comment]
Hi,
Thank you for reporting this.
1. Did you see this just once or more often? 
2. Can you please turn on debug log and post the relevant debug log lines once you see this warn log line (`Please open a issue on Github`) again?

Just as a note: Per the log, it looks like that your Huawei tablet does not have a stable connection. In my tests with multiple tablets, I see `... is not alive!` very rarely in the log (0-1x per day - if at all).

**Comment by Ilovegym66** [comment]
Hi, 
1) yes, more times, also with other devices, too
2) this morning I found an error in the log, I changed to debug, restarted, and the error appears again:
```
2023-04-04 08:34:17.389  - debug: fully-mqtt.0 (139413) [MQTT] client.conn.remoteAddress = "::ffff:10.1.1.50" - Huawei-FlurOG
2023-04-04 08:34:17.390  - debug: fully-mqtt.0 (139413) [MQTT] Client Huawei-FlurOG (10.1.1.50) trys to authenticate...
2023-04-04 08:34:17.390  - info: fully-mqtt.0 (139413) 🔑 MQTT Client Huawei-FlurOG (10.1.1.50) successfully authenticated.
2023-04-04 08:34:17.390  - debug: fully-mqtt.0 (139413) [MQTT] Client Huawei-FlurOG (10.1.1.50) connected to broker adc4a2f6-8fdb-460d-aed1-15a5a191e77f
2023-04-04 08:34:17.390  - info: fully-mqtt.0 (139413) 🔗 MQTT Client Huawei-FlurOG (10.1.1.50) successfully connected.
2023-04-04 08:34:17.391  - info: fully-mqtt.0 (139413) Huawei-FlurOG is alive (MQTT: client connected)
2023-04-04 08:34:18.383  - debug: fully-mqtt.0 (139413) [MQTT] Client GalaxyTabGastDG = GalaxyTabGastDG = 10.1.1.42
2023-04-04 08:34:18.384  - debug: fully-mqtt.0 (139413) [MQTT] GalaxyTabGastDG published info, topic: fully/deviceInfo/44edf011-8cec2ce
2023-04-04 08:34:18.403  - debug: fully-mqtt.0 (139413) [MQTT] GalaxyTabGastDG: Initially create states for 67 info items (if not yet existing)
2023-04-04 08:34:18.383  - debug: fully-mqtt.0 (139413) [MQTT] Client GalaxyTabGastDG = GalaxyTabGastDG = 10.1.1.42
2023-04-04 08:34:18.384  - debug: fully-mqtt.0 (139413) [MQTT] GalaxyTabGastDG published info, topic: fully/deviceInfo/44edf011-8cec2ce
2023-04-04 08:34:18.403  - debug: fully-mqtt.0 (139413) [MQTT] GalaxyTabGastDG: Initially create states for 67 info items (if not yet existing)
2023-04-04 08:34:21.931  - info: javascript.0 (9926) script.js.common.Nuki.mqtt2log: NUKI Hub WT: Querying lock state: unlocked
2023-04-04 08:34:22.164  - error: fully-mqtt.0 (139413) TypeError: Cannot read properties of undefined (reading 'name')
    at Aedes.<anonymous> (/opt/iobroker/node_modules/iobroker.fully-mqtt/build/lib/mqtt-server.js:128:59)
    at Aedes.emit (node:events:513:28)
    at PublishState.callPublished (/opt/iobroker/node_modules/aedes/aedes.js:255:15)
    at makeCallTwo (/opt/iobroker/node_modules/fastseries/series.js:150:3)
    at MQEmitter.release (/opt/iobroker/node_modules/fastseries/series.js:138:7)
    at MQEmitter.parallel [as _parallel] (/opt/iobroker/node_modules/fastparallel/parallel.js:25:12)
    at MQEmitter._do (/opt/iobroker/node_modules/mqemitter/mqemitter.js:133:8)
    at MQEmitter.emit (/opt/iobroker/node_modules/mqemitter/mqemitter.js:115:10)
    at PublishState.emitPacket (/opt/iobroker/node_modules/aedes/aedes.js:194:18)
    at makeCallTwo (/opt/iobroker/node_modules/fastseries/series.js:150:3)
2023-04-04 08:34:21.931  - info: javascript.0 (9926) script.js.common.Nuki.mqtt2log: NUKI Hub WT: Querying lock state: unlocked
2023-04-04 08:34:22.164  - error: fully-mqtt.0 (139413) TypeError: Cannot read properties of undefined (reading 'name')
    at Aedes.<anonymous> (/opt/iobroker/node_modules/iobroker.fully-mqtt/build/lib/mqtt-server.js:128:59)
    at Aedes.emit (node:events:513:28)
    at PublishState.callPublished (/opt/iobroker/node_modules/aedes/aedes.js:255:15)
    at makeCallTwo (/opt/iobroker/node_modules/fastseries/series.js:150:3)
    at MQEmitter.release (/opt/iobroker/node_modules/fastseries/series.js:138:7)
    at MQEmitter.parallel [as _parallel] (/opt/iobroker/node_modules/fastparallel/parallel.js:25:12)
    at MQEmitter._do (/opt/iobroker/node_modules/mqemitter/mqemitter.js:133:8)
    at MQEmitter.emit (/opt/iobroker/node_modules/mqemitter/mqemitter.js:115:10)
    at PublishState.emitPacket (/opt/iobroker/node_modules/aedes/aedes.js:194:18)
    at makeCallTwo (/opt/iobroker/node_modules/fastseries/series.js:150:3)
2023-04-04 08:34:22.819  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:22.819  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:25.250  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:25.250  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:25.878  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:25.878  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:27.101  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:27.101  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
```

here the wifi connection state:
![image](https://user-images.githubusercontent.com/36229898/229708905-075e22d3-a8cc-43c8-86bf-57e9683dcb8c.png)

3) yes, the wifi was not stable, I changed the AP and lock it, now on the Tablet above the connection is fine, but the fault stays..
I have the fault on one Tablet which is connected via LAN, too.. so it's looks like more a timing as a connection problem?


_(edited by Acgua: added tag for multiple line code)_

**Comment by Acgua** [comment]
Thank you Ilovegym66, I appreciate your test and feedback!

I was able to identify the cause of the error and likely also what caused the "this should never happen" log line. I finally will also need to extend my tests and test cases to get this stable and under control.

I will post an update here once completed.

**Comment by Acgua** [comment]
Just as a side note:
```
2023-04-04 08:34:22.819  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:22.819  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:25.250  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:25.250  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:25.878  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:25.878  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:27.101  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
2023-04-04 08:34:27.101  - debug: fully-mqtt.0 (139413) [MQTT] 📡 GalaxyTabOGB published event, topic: fully/event/facesDetected/56b3894e-909435b, cmd: facesDetected
```
Your Tablet `GalaxyTabOGB` is publishing `facesDetected` multiple times within just a few milliseconds. I have seen too many publishings before, but after restarting Fully Browser app (or Android itself) it was gone. This is not adapter related, but caused by Fully app. 
Anyway, I can't influence what the Fully app is doing, but I will include a verification of such multiple calls in the code.

**Comment by Ilovegym66** [comment]
Error is solved since js-Controller 5.x
